### ISSUE TITLE
PRECISA CORRIGIR!

### ISSUE THREAD

**Issue by evssousa** [gMarinhum085/criando-um-artigo#1]
Vi que no seu código tem um "hi" no lugar de h1.
Outra, faz a troca dos h5, os únicos h que tem é h1 e h2.
As imagens também estão pequenas. Deixar elas no tamanho original.

**Comment by evssousa** [comment]
Nome do projeto errado!

**Comment by GabrielMarinho0516** [comment]
Corrigido
